//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFZRBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class combat_turn
    {
        public string player_id { get; set; }
        public string monster_id { get; set; }
        public int turn { get; set; }
        public Nullable<double> player_dmg { get; set; }
        public Nullable<double> monster_dmg { get; set; }
    
        public virtual combat combat { get; set; }
    }
}
