//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFZRBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class combat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public combat()
        {
            this.combat_turn = new HashSet<combat_turn>();
        }
    
        public string player_id { get; set; }
        public string monster_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<bool> player_win { get; set; }
    
        public virtual monster monster { get; set; }
        public virtual player player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<combat_turn> combat_turn { get; set; }
    }
}
