//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFZRBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_drop
    {
        public string area_id { get; set; }
        public string skill_id_need { get; set; }
        public string item_id { get; set; }
        public Nullable<double> item_drop_chance { get; set; }
        public Nullable<int> skill_level_need { get; set; }
    
        public virtual area area { get; set; }
        public virtual item item { get; set; }
        public virtual skill skill { get; set; }
    }
}
