//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFZRBot.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ifzrtempEntities : DbContext
    {
        public ifzrtempEntities()
            : base("name=ifzrtempEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<combat> combats { get; set; }
        public virtual DbSet<combat_turn> combat_turn { get; set; }
        public virtual DbSet<equip_type> equip_type { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<item_drop> item_drop { get; set; }
        public virtual DbSet<Item_type> Item_type { get; set; }
        public virtual DbSet<monster> monsters { get; set; }
        public virtual DbSet<monster_drop> monster_drop { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<player_equip> player_equip { get; set; }
        public virtual DbSet<player_inventory> player_inventory { get; set; }
        public virtual DbSet<player_skill> player_skill { get; set; }
        public virtual DbSet<skill> skills { get; set; }
    }
}
