//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFZRBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public monster()
        {
            this.combats = new HashSet<combat>();
            this.monster_drop = new HashSet<monster_drop>();
            this.areas = new HashSet<area>();
        }
    
        public string monster_id { get; set; }
        public string monster_name { get; set; }
        public Nullable<int> monster_str { get; set; }
        public Nullable<int> monster_agi { get; set; }
        public Nullable<int> monster_int { get; set; }
        public Nullable<double> monster_max_hp { get; set; }
        public Nullable<double> monster_atk { get; set; }
        public Nullable<double> monster_arm { get; set; }
        public Nullable<double> monster_crit { get; set; }
        public Nullable<double> monster_critdmg { get; set; }
        public Nullable<double> monster_eva { get; set; }
        public Nullable<long> monster_exp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<combat> combats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<monster_drop> monster_drop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<area> areas { get; set; }
    }
}
