//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFZRBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_equip
    {
        public string player_id { get; set; }
        public string item_id { get; set; }
        public string equip_type_id { get; set; }
    
        public virtual equip_type equip_type { get; set; }
        public virtual item item { get; set; }
        public virtual player player { get; set; }
    }
}
