//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFZRBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public player()
        {
            this.combats = new HashSet<combat>();
            this.player_equip = new HashSet<player_equip>();
            this.player_inventory = new HashSet<player_inventory>();
            this.player_skill = new HashSet<player_skill>();
        }
    
        public string player_id { get; set; }
        public string player_location { get; set; }
        public string player_name { get; set; }
        public Nullable<int> player_stat_point { get; set; }
        public Nullable<int> player_level { get; set; }
        public Nullable<long> player_exp { get; set; }
        public Nullable<long> player_exp_next_lv { get; set; }
        public Nullable<int> player_str { get; set; }
        public Nullable<int> player_agi { get; set; }
        public Nullable<int> player_int { get; set; }
        public Nullable<double> player_atk { get; set; }
        public Nullable<double> player_arm { get; set; }
        public Nullable<double> player_max_hp { get; set; }
        public Nullable<double> player_hp { get; set; }
        public Nullable<double> player_crit { get; set; }
        public Nullable<double> player_critdmg { get; set; }
        public Nullable<double> player_eva { get; set; }
    
        public virtual area area { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<combat> combats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player_equip> player_equip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player_inventory> player_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player_skill> player_skill { get; set; }
    }
}
